### PR TITLE
Replace multiskin optional dependency with skinsdb

### PR DESCRIPTION
**Pull request by dacmot**

### CODE REVIEW

**Comment by sfence** [comment]
`Skinsdb` mod has `clothing` mod as a dependency.

Adding `skinsdb` to a dependency list of `clothing` will cause circular dependency.

**Comment by dacmot** [comment]
Ah. Well, that's a problem that needs addressing. Whether it's declared or not in mod.conf, a circular dependency should not happen.

Do you think it's something that should be corrected on the skinsdb side?

-Olivier

-------- Message d'origine --------

**Comment by sfence** [comment]
There is this code in skinsdb: 

https://github.com/minetest-mods/skinsdb/blob/cd27e24b6f0275c015487b4998dcfc8932baf8c0/skin_meta_api.lua#L175-L187

I do not think, that it can be easily removed and replaced.

**Comment by dacmot** [comment]
You're right. Doesn't make much sense.

On the other hand, it looks to me like the dependency on skinsdb in this mod is extraneous. Clothing is about adding clothes, not skins. If people want a naked skin, they should be able to use one, sure. But I don't think it should be the clothing mod's job to make it available.

In any case, I digress.

**Comment by sfence** [comment]
What is the reason for removing multiskin dependency?

**Comment by dacmot** [comment]
Arrgh. Sorry. Github's terrible search made me believe there was no more references to the word "multiskin." I'll fix it when I get home after work.

-------- Message d'origine --------

**Comment by sfence** [comment]
@dacmot 
Clothing just often looks weird on default skin, in my experience.
It is a reason why I added skins in underwear.

If somebody wants naked skins, it should be done in a separate mod with a gore flag in contentdb probably.

**Comment by dacmot** [comment]
By "naked" I meant the skins you added "in underwear." My point was that I don't think it's a great idea to add skins in your mod. The clothing mod is well defined (clothing of different colours, tools like loom, etc.) but the extra skins don't fit in that frame. Plus it creates an implicit circular dependency with skinsdb. To me it seems preferable that it was upstreamed to skinsdb instead.

**Comment by sfence** [comment]
Yes and no.

To use skinsdb skins, you have to be an advanced user because you have to download those skins manually or by a script running.
I expect, that the typical clothing user would be able to download these two mods from the Minetest menu and start the world with these mods enabled. So, it makes him comfortable if "underwear" skins are simply available for him and clothing does not collide with the default skin.

In the case of moving these skins to skinsdb database, users will have to download the skins database by running Python script or by allowing the skinsdb mod as trusted for HTTPS API, using the in-game command and going through the list of hundreds of skins to find the usable ones.

**Comment by dacmot** [comment]
I did not know what to respond to you at the time. With some time and perspective, I'd like to clarify my thoughts.

My dilemma is that I like this mod's improvements, but I don't think we can include it as is in our WhyNot game. Maybe I could not verbalize my idea on how to resolve the issue properly before. I hope this can help.

You added the underwear skins to this mod, so it should be possible to add it to skinsdb in the same way. Or maybe split it off into a third mod to break that circular dependency. This would also make it optional without the need for a (non-intuitive) config variable.

The downsides are having to maintain two mods, and the loss of discoverability or strong recommendation, but it could be somewhat mitigated by adding notes in the clothing readme, forums and contentdb page.

```
clothing
   ^   ^
   |   |
   |   |
skindb |
   ^   |
   |   |
   |   |
bareskins (underwear)
```

**Pull request merged**
